server:
  port: 18081

spring:
  application:
    name: demo-service-a

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
